# from BSDI Makefile,v 2.6 1996/04/08 20:06:40 bostic Exp
#
# $FreeBSD: projects/doscmd/Makefile,v 1.39 2004/03/30 17:10:01 des Exp $

LIB=	udis86
WARNS?=	2
SRCS=	itab.c input.c decode.c syn.c syn-intel.c syn-att.c udis86.c
INCS=	udis86.h types.h extern.h itab.h
INCSDIR= ${INCLUDEDIR}/udis86

.include <bsd.lib.mk>
